AddonId: BattlenetLibrary_Builtin
Packages:
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-24
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/BattlenetLibrary_Builtin_2_2.pext
    Changelog:
      - Updated dependencies for Playnite 9
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-08
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/1.0/BattlenetLibrary_Builtin_2_1.pext
    Changelog:
      - Updated to support Playnite 9 beta 2
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-03
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/1.0/BattlenetLibrary_Builtin_2_0.pext
    Changelog:
      - Playnite 9 support
  - Version: 2.3
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-11-06
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/BattlenetLibrary_Builtin_2_3.pext
    Changelog:
      - Added support for Call of Duty Vanguard
  - Version: 2.4
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2022-04-16
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/BattlenetLibrary_Builtin_2_4.pext
    Changelog:
      - Game startup should be more reliable if the client is not running prior to launching a game 
  - Version: 2.5
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2022-05-10
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/BattlenetLibrary_Builtin_2_5.pext
    Changelog:
      - Play time tracking could start sooner than it should (by darklinkpower)
  - Version: 2.6
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2022-06-02
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/BattlenetLibrary_Builtin_2_6.pext
    Changelog:
      - Added Diablo Immortal support
  - Version: 2.7
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2022-06-09
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/BattlenetLibrary_Builtin_2_7.pext
    Changelog:
      - Removed classic Warcraft 3 entires and fixed tracking of Reforged version
      - Fixed a crash when tracking a game
  - Version: 2.8
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2022-06-11
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/BattlenetLibrary_Builtin_2_8.pext
    Changelog:
      - Fixed import of uninstalled games failing
  - Version: 2.9
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2022-10-05
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/BattlenetLibrary_Builtin_2_9.pext
    Changelog:
      - Renamed Overwatch to Overwatch 2 (doesn't affect already imported Overwatch entry)
  - Version: 2.10
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2022-11-01
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/BattlenetLibrary_Builtin_2_10.pext
    Changelog:
      - Added Modern Warfare II support
  - Version: 2.11
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2023-06-01
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/BattlenetLibrary_Builtin_2_11.pext
    Changelog:
      - Added Diablo IV support
  - Version: 2.12
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2023-07-13
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/BattlenetLibrary_Builtin_2_12.pext
    Changelog:
      - Restored support for classic (pre Reforged) Warcraft 3 versions
  - Version: 2.13
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2023-10-23
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/BattlenetLibrary_Builtin_2_13.pext
    Changelog:
      - Tweaked game startup procedure to make it more reliable
  - Version: 2.14
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2023-10-23
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/BattlenetLibrary_Builtin_2_14.pext
    Changelog:
      - Started game process ID is passed properly to OnStarted event (by lscholte)