AddonId: GogLibrary_Builtin
Packages:
  - Version: 2.20
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2025-06-13
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/GogLibrary_Builtin_2_20.pext
    Changelog:
      - Fixed handling of some game DLCs (by hawkeye116477)
      - Fixed automatic install process no longer working (by darklinkpower)
  - Version: 2.21
    RequiredApiVersion: 6.14.0
    ReleaseDate: 2025-12-03
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/GogLibrary_Builtin_2_21.pext
    Changelog:
      - Added option to import non-game library items as separate game entires (by Rast1234)