AddonId: HumbleLibrary_Builtin
Packages:
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-03
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/1.0/HumbleLibrary_Builtin_2_0.pext
    Changelog:
      - Playnite 9 support
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-08
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/1.0/HumbleLibrary_Builtin_2_1.pext
    Changelog:
      - Updated to support Playnite 9 beta 2
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-24
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/HumbleLibrary_Builtin_2_2.pext
    Changelog:
      - Updated dependencies for Playnite 9
  - Version: 3.0
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-02-01
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/HumbleLibrary_Builtin_3_0.pext
    Changelog:
      - Added support for new Humble App
      - Added support for new Humble Choice subscription
      - Improved general import speed
  - Version: 3.1
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-02-01
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/HumbleLibrary_Builtin_3_1.pext
    Changelog:
      - Fixed Humble library icon not showing up properly when set as missing game icon
  - Version: 3.2
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-02-02
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/HumbleLibrary_Builtin_3_2.pext
    Changelog:
      - Fixed Humble App being selectable install option for non-Humble games
  - Version: 3.3
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-02
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/HumbleLibrary_Builtin_3_3.pext
    Changelog:
      - Game import fails when Humble App is downloading games
  - Version: 3.4
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-07
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/HumbleLibrary_Builtin_3_4.pext
    Changelog:
      - Certain games don't launch or install
  - Version: 3.5
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-16
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/HumbleLibrary_Builtin_3_5.pext
    Changelog:
      - Fixed games incorrectly marked as installed (by darklinkpower)
  - Version: 3.6
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-05-26
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/HumbleLibrary_Builtin_3_6.pext
    Changelog:
      - Fixed game import failing
      - Fixed crash when installing or uninstalling a game
  - Version: 3.7
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-07-06
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/HumbleLibrary_Builtin_3_7.pext
    Changelog:
      - Fixed library import failing with some accounts