AddonId: HumbleLibrary_Builtin
Packages:
  - Version: 3.7
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-07-06
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/HumbleLibrary_Builtin_3_7.pext
    Changelog:
      - Fixed library import failing with some accounts
  - Version: 3.8
    RequiredApiVersion: 6.14.0
    ReleaseDate: 2025-12-03
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/HumbleLibrary_Builtin_3_8.pext
    Changelog:
      - Added option to import non-game library items as separate game entires (by Rast1234)