AddonId: IGDBMetadata_Builtin
Packages:
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-24
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/IGDBMetadata_Builtin_2_2.pext
    Changelog:
      - Manual metadata search doesn't work in some cases
      - Updated dependencies for Playnite 9
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-08
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/1.0/IGDBMetadata_Builtin_2_1.pext
    Changelog:
      - Metadata download doesn't work properly in some cases
      - Updated to support Playnite 9 beta 2
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-03
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/1.0/IGDBMetadata_Builtin_2_0.pext
    Changelog:
      - Playnite 9 support
  - Version: 2.3
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-22
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/IGDBMetadata_Builtin_2_3.pext
    Changelog:
      - Fixed metadata download failing for some games
  - Version: 2.4
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-12-17
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/IGDBMetadata_Builtin_2_4.pext
    Changelog:
      - Name field support for bulk downloads
  - Version: 2.5
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2022-04-19
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/IGDBMetadata_Builtin_2_5.pext
    Changelog:
      - Added ability to search for games by their ID
  - Version: 2.6
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2023-03-09
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/IGDBMetadata_Builtin_2_6.pext
    Changelog:
      - Fixed image downloads not working
  - Version: 2.7
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-06-09
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/IGDBMetadata_Builtin_2_7.pext
    Changelog:
      - Completely reworked game matching and search
      - Added support for searching games via global search ("i" as default keyword)
      - Added option to use cropped cover images as icons (opt in)
  - Version: 2.8
    RequiredApiVersion: 6.5.0
    ReleaseDate: 2023-06-26
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/IGDBMetadata_Builtin_2_8.pext
    Changelog:
      - Lowered minimum required Playnite version
  - Version: 2.9
    RequiredApiVersion: 6.5.0
    ReleaseDate: 2023-10-23
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/IGDBMetadata_Builtin_2_9.pext
    Changelog:
      - Show game port information on search results