AddonId: ItchioLibrary_Builtin
Packages:
  - Version: 2.7
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2024-01-08
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/ItchioLibrary_Builtin_2_7.pext
    Changelog:
      - Installing a game starts installation directly in itch client now (by burnhamup)