AddonId: OriginLibrary_Builtin
Packages:
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-24
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/OriginLibrary_Builtin_2_2.pext
    Changelog:
      - Updated dependencies for Playnite 9
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-08
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/1.0/OriginLibrary_Builtin_2_1.pext
    Changelog:
      - Updated to support Playnite 9 beta 2
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-03
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/1.0/OriginLibrary_Builtin_2_0.pext
    Changelog:
      - Playnite 9 support
  - Version: 2.3
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-12
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/OriginLibrary_Builtin_2_3.pext
    Changelog:
      - Canceling library sync takes too long
      - Minor fix to import of installed games
  - Version: 2.4
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-12-17
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/OriginLibrary_Builtin_2_4.pext
    Changelog:
      - Fixed opening Origin client starting EA Desktop instead if it's installed
  - Version: 2.5
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-12-20
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/OriginLibrary_Builtin_2_5.pext
    Changelog:
      - Fixed Origin client detection failing
  - Version: 2.6
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2022-05-10
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/OriginLibrary_Builtin_2_6.pext
    Changelog:
      - Play time tracking could start sooner than it should (by darklinkpower)
  - Version: 2.7
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2022-10-19
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/OriginLibrary_Builtin_2_7.pext
    Changelog:
      - EA app support
      - Origin is still mostly supported, but if you haven't updated and you use Origin, DO NOT update to this version for better compatibility
      - Import of installed games now requires connected account
  - Version: 2.8
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2022-10-21
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/OriginLibrary_Builtin_2_8.pext
    Changelog:
      - Fixed authentication not working
  - Version: 2.9
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2023-01-12
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/OriginLibrary_Builtin_2_9.pext
    Changelog:
      - Fixed authentication not working
  - Version: 2.10
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2023-01-21
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/OriginLibrary_Builtin_2_10.pext
    Changelog:
      - Fixed issue with games using EasyAntiCheat not starting properly
  - Version: 2.11
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2023-10-23
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/OriginLibrary_Builtin_2_11.pext
    Changelog:
      - Started game process ID is passed properly to OnStarted event (by lscholte)
  - Version: 2.12
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2023-11-08
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/OriginLibrary_Builtin_2_12.pext
    Changelog:
      - EA Sports WRC fails to import