AddonId: SteamLibrary_Builtin
Packages:
  - Version: 2.37
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2025-11-21
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_37.pext
    Changelog:
      - Fixed web login sync failing in some cases (by Jeshibu)
  - Version: 2.38
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2025-11-25
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_38.pext
    Changelog:
      - Added option to disable import of family shared games
  - Version: 2.39
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2025-12-01
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_39.pext
    Changelog:
      - Fixed plugin overwriting custom sources assigned to Steam games (by Jeshibu)
  - Version: 2.40
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2025-12-05
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_40.pext
    Changelog:
      - Don't create Steam game source if not necessary (by Jeshibu)