AddonId: SteamLibrary_Builtin
Packages:
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-24
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_2.pext
    Changelog:
      - Updated dependencies for Playnite 9
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-08
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/1.0/SteamLibrary_Builtin_2_1.pext
    Changelog:
      - Updated to support Playnite 9 beta 2
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-03
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/1.0/SteamLibrary_Builtin_2_0.pext
    Changelog:
      - Playnite 9 support
  - Version: 2.3
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-29
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_3.pext
    Changelog:
      - Franchine field from Steam is used to populate Series field
      - Small optimization to metadata download
      - Fixed private API keys leaking to logs
  - Version: 2.4
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2022-01-03
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_4.pext
    Changelog:
      - Use game descriptions without promotion junk
      - Prioritize English localized game names
      - Fixed crash when installing or uninstalling a game and Steam installation is not detected
      - Fixed newly added games have "Last Played" set to date where they were bought
      - Fixed (Re)Import of Steam categories does not take into account games where categories have been removed in Steam
  - Version: 2.5
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2022-04-16
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_5.pext
    Changelog:
      - Added ability to ignore installed games from other accounts
      - Added ability to import games from additional Steam accounts
  - Version: 2.6
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2022-05-10
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_6.pext
    Changelog:
      - Play time tracking could start sooner than it should (by darklinkpower)
      - Ignore Franchises that contain a developer or publisher name from being added as series (by darklinkpower)
      - Fixed series field being incorrectly imported with encoded HTML characters
  - Version: 2.7
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2022-06-09
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_7.pext
    Changelog:
      - Fixed installed source mods not being imported under certain conditions
      - Fixed a crash when tracking a game
  - Version: 2.8
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2022-06-21
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_8.pext
    Changelog:
      - Small optimization to import of installed games
  - Version: 2.9
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2022-11-15
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_9.pext
    Changelog:
      - Added support for localized metadata (by Jeshibu)
      - Added support for import of store tags (by Jeshibu)
      - Metadata for demos are now downloaded from main game (by Jeshibu)
  - Version: 2.10
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2022-12-07
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_10.pext
    Changelog:
      - Added an option to show Steam game startup selection dialog (by Jeshibu and CanRanBan)
      - Fixed metadata download issues related to some games (by Jeshibu)
  - Version: 2.11
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2023-03-04
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_11.pext
    Changelog:
      - Added support for download of supported platforms (by Jeshibu)
      - Fixed imprecise release date parsing (by Jeshibu)
      - Fixed issue with being unable to re-authenticate under a different Steam account
  - Version: 2.12
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2023-04-26
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_12.pext
    Changelog:
      - Fixed games being detected as installed before fully downloaded
  - Version: 2.13
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2023-05-01
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_13.pext
    Changelog:
      - Removed problematic background image source
  - Version: 2.14
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2023-05-03
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_14.pext
    Changelog:
      - Better handling of problematic sources for background image
      - Fixed issue slowing down metadata download in some cases
  - Version: 2.15
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2023-06-09
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_15.pext
    Changelog:
      - Fixed "Ignore installed games from other accounts" option not working properly if no additional accounts are set
  - Version: 2.16
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2023-06-22
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_16.pext
    Changelog:
      - Tag handling fixes by Jeshibu
  - Version: 2.17
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2023-08-15
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_17.pext
    Changelog:
      - Fix detection of some Half-Life mods (by psychonic)
  - Version: 2.18
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2023-08-16
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_18.pext
    Changelog:
      - Force Steam to launch minimized when starting a game while Steam is not running
  - Version: 2.19
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2023-10-23
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_19.pext
    Changelog:
      - Added Indonesian language (by Jeshibu)
      - API keys no longer stored in plugin config
  - Version: 2.20
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2023-10-23
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_20.pext
    Changelog:
      - Added option to download Deck compatibility metadata (by Jeshibu)
      - Added option to add tag category as prefix (by darklinkpower)
      - Started game process ID is passed properly to OnStarted event (by lscholte)
      - Removed option to import categories from Steam install
  - Version: 2.21
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2023-10-23
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_21.pext
    Changelog:
      - Some localized strings not showing
  - Version: 2.22
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2023-10-23
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_22.pext
    Changelog:
      - Fixed plugin failing to load in some cases
  - Version: 2.23
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2023-11-29
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_23.pext
    Changelog:
      - Fixed plugin failing to load after update if additional accounts are not configured properly
  - Version: 2.24
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2024-09-20
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_24.pext
    Changelog:
      -  Fixed Steam Deck compatibility null reference exception when api game details call fails (by Jeshibu)
  - Version: 2.25
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2024-10-31
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_25.pext
    Changelog:
      -  Fixed UI freezes during Uninstall (by darklinkpower)
      -  Library update and metadata download game name fixes (by darklinkpower)
  - Version: 2.26
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2025-01-03
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_26.pext
    Changelog:
      - Import error from extra accounts doesn't fail the entire import process anymore   
  - Version: 2.27
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2025-05-20
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_27.pext
    Changelog:
      - Reworked authentication and import of games when not using API key. You may need to re-authenticate after this update if you are not using your own API key.
  - Version: 2.28
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2025-05-22
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_28.pext
    Changelog:
      - Fixed Steam source not being assigned when using web login
  - Version: 2.29
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2025-06-13
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_29.pext
    Changelog:
      - Better indication of authentication status
  - Version: 2.30
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2025-06-13
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_30.pext
    Changelog:
      - Added automated retry in case of 429 error during library update
  - Version: 2.31
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2025-07-05
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_31.pext
    Changelog:
      - Games with unknown developer or publisher won't have "N/A" value assigned anymore (by darklinkpower)
  - Version: 2.32
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2025-09-22
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_32.pext
    Changelog:
      - Fixed issues with description images not rendering properly (will still require Playnite update to fix certain images rendering corrupted).
  - Version: 2.33
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2025-10-12
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_33.pext
    Changelog:
      - Added option to configure list of game ids to import "manually". As a workaround for games where Steam API doesn't return specific games as part of user's library.
  - Version: 2.34
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2025-10-27
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_34.pext
    Changelog:
      - Fixed description images sometimes don't displaying at correct aspect ratio
  - Version: 2.35
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2025-11-13
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_35.pext
    Changelog:
      - Fixed web authentication method not working (by Jeshibu)
      - Added support for drag and drop from Steam's game list into custom ID import list field (by Rast1234)
  - Version: 2.36
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2025-11-21
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_36.pext
    Changelog:
      - Fixed some games (mostly free ones) not being imported by improving web login method (by Jeshibu)
      - Web login method now imports family shared games (by Jeshibu)
  - Version: 2.37
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2025-11-21
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_37.pext
    Changelog:
      - Fixed web login sync failing in some cases (by Jeshibu)
  - Version: 2.38
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2025-11-25
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_38.pext
    Changelog:
      - Added option to disable import of family shared games
  - Version: 2.39
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2025-12-01
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_39.pext
    Changelog:
      - Fixed plugin overwriting custom sources assigned to Steam games (by Jeshibu)
  - Version: 2.40
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2025-12-05
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_40.pext
    Changelog:
      - Don't create Steam game source if not necessary (by Jeshibu)