AddonId: SteamLibrary_Builtin
Packages:
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-24
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_2.pext
    Changelog:
      - Updated dependencies for Playnite 9
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-08
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/1.0/SteamLibrary_Builtin_2_1.pext
    Changelog:
      - Updated to support Playnite 9 beta 2
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-03
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/1.0/SteamLibrary_Builtin_2_0.pext
    Changelog:
      - Playnite 9 support
  - Version: 2.3
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-29
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_3.pext
    Changelog:
      - Franchine field from Steam is used to populate Series field
      - Small optimization to metadata download
      - Fixed private API keys leaking to logs
  - Version: 2.4
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2022-01-03
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_4.pext
    Changelog:
      - Use game descriptions without promotion junk
      - Prioritize English localized game names
      - Fixed crash when installing or uninstalling a game and Steam installation is not detected
      - Fixed newly added games have "Last Played" set to date where they were bought
      - Fixed (Re)Import of Steam categories does not take into account games where categories have been removed in Steam
  - Version: 2.5
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2022-04-16
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_5.pext
    Changelog:
      - Added ability to ignore installed games from other accounts
      - Added ability to import games from additional Steam accounts
  - Version: 2.6
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2022-05-10
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_6.pext
    Changelog:
      - Play time tracking could start sooner than it should (by darklinkpower)
      - Ignore Franchises that contain a developer or publisher name from being added as series (by darklinkpower)
      - Fixed series field being incorrectly imported with encoded HTML characters
  - Version: 2.7
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2022-06-09
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_7.pext
    Changelog:
      - Fixed installed source mods not being imported under certain conditions
      - Fixed a crash when tracking a game
  - Version: 2.8
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2022-06-21
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/SteamLibrary_Builtin_2_8.pext
    Changelog:
      - Small optimization to import of installed games