AddonId: Universal_Steam_Metadata
Packages:
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-24
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/Universal_Steam_Metadata_2_2.pext
    Changelog:
      - Updated dependencies for Playnite 9
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-08
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/1.0/Universal_Steam_Metadata_2_1.pext
    Changelog:
      - Metadata download of some specific games fails
      - Updated to support Playnite 9 beta 2
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-03
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/1.0/Universal_Steam_Metadata_2_0.pext
    Changelog:
      - Playnite 9 support
  - Version: 2.3
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-29
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/Universal_Steam_Metadata_2_3.pext
    Changelog:
      - Franchine field from Steam is used to populate Series field
      - Small optimization to metadata download
  - Version: 2.4
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2022-01-03
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/Universal_Steam_Metadata_2_4.pext
    Changelog:
      - Use game descriptions without promotion junk
      - Prioritize English localized game names
  - Version: 2.5
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2022-05-10
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/Universal_Steam_Metadata_2_5.pext
    Changelog:
      - Ignore Franchises that contain a developer or publisher name from being added as series (by darklinkpower)
      - Fixed series field being incorrectly imported with encoded HTML characters
  - Version: 2.6
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2022-06-21
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/Universal_Steam_Metadata_2_6.pext
    Changelog:
      - Fixed issue with some link names not being imported correctly if Steam library plugin is not installed
  - Version: 2.7
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2022-11-15
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/Universal_Steam_Metadata_2_7.pext
    Changelog:
      - Added support for localized metadata (by Jeshibu)
      - Added support for import of store tags (by Jeshibu)
      - Metadata for demos are now downloaded from main game (by Jeshibu)
  - Version: 2.8
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2022-12-07
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/Universal_Steam_Metadata_2_8.pext
    Changelog:
      - Fixed metadata download issues related to some games (by Jeshibu)
  - Version: 2.9
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2023-03-04
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/Universal_Steam_Metadata_2_9.pext
    Changelog:
      - Added support for download of supported platforms (by Jeshibu)
      - Fixed imprecise release date parsing (by Jeshibu)
  - Version: 2.10
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2023-05-01
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/Universal_Steam_Metadata_2_10.pext
    Changelog:
      - Removed problematic background image source
  - Version: 2.11
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2023-05-03
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/Universal_Steam_Metadata_2_11.pext
    Changelog:
      - Better handling of problematic sources for background image
      - Fixed issue slowing down metadata download in some cases
  - Version: 2.12
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2023-06-22
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/Universal_Steam_Metadata_2_12.pext
    Changelog:
      - Tag handling fixes by Jeshibu
  - Version: 2.13
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2023-10-23
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/Universal_Steam_Metadata_2_13.pext
    Changelog:
      - Added Indonesian language (by Jeshibu)
      - Fixed incorrect searches when game name has characters that need encoding (by darklinkpower)
  - Version: 2.14
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2023-10-23
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/Universal_Steam_Metadata_2_14.pext
    Changelog:
      - Added option to download Deck compatibility metadata (by Jeshibu)
      - Added option to add tag category as prefix (by darklinkpower)