AddonId: UplayLibrary_Builtin
Packages:
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-03
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/1.0/UplayLibrary_Builtin_2_0.pext
    Changelog:
      - Playnite 9 support
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-08
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/1.0/UplayLibrary_Builtin_2_1.pext
    Changelog:
      - Updated to support Playnite 9 beta 2
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-24
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/UplayLibrary_Builtin_2_2.pext
    Changelog:
      - Updated dependencies for Playnite 9
  - Version: 2.3
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2022-05-10
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/UplayLibrary_Builtin_2_3.pext
    Changelog:
      - Play time tracking could start sooner than it should (by darklinkpower)
  - Version: 2.4
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2022-12-01
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/UplayLibrary_Builtin_2_4.pext
    Changelog:
      - Removed string references to Uplay client (by Xenor)
  - Version: 2.5
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2023-03-06
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/UplayLibrary_Builtin_2_5.pext
    Changelog:
      - Fixed R6 Siege not being tracked properly
  - Version: 2.6
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2023-10-23
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/UplayLibrary_Builtin_2_6.pext
    Changelog:
      - Started game process ID is passed properly to OnStarted event (by lscholte)