AddonId: XboxLibrary_Builtin
Packages:
  - Version: 2.15
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2024-09-02
    PackageUrl: https://github.com/JosefNemec/PlayniteExtensions/releases/download/2.2/XboxLibrary_Builtin_2_15.pext
    Changelog:
      - Import of installed games failing sometimes